### PR TITLE
dark/light mode added

### PR DESCRIPTION
**Pull request by Bib3k4u**

### CODE REVIEW

**Review by slzakaria — CHANGES_REQUESTED** [review]
Can you please resolve the conflicting merge issues ?

If it helps, save your code , pull the latest changes from the repo and rebase then re add your code

**Comment by Bib3k4u** [comment]
Actually I'm new here but I'm trying.
If I get stuck please help me out

**Comment by slzakaria** [comment]
@Bib3k4u hope this helps [https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)

**Comment by Bib3k4u** [comment]
Yes, it does.
Thankyou.
I have raised the PR again please do ✅

**Pull request closed without merging**
